### ISSUE TITLE
你好，请教一个问题

### ISSUE THREAD

**Issue by yejuns** [huangdali/HRichEditor#2]
为什么我用您的demo上传图片到服务器，上传的图片只能传1k，接口用postman测试是没有问题的，关键代码是：
       EditorResultBean resultBean=(EditorResultBean)data.getSerializableExtra("contents");
        ELog.e(resultBean);
        List<EContent> contents=resultBean.getContents();
        EContent content=contents.get(0);
        String  imageUrl=content.getUrl().isEmpty()?null:content.getUrl();
        String  describe=content.getContent().isEmpty()?null:content.getContent();
        Log.e("url",imageUrl);
        upImage(imageUrl,describe);//上传图片与关键信息
谢谢。

**Comment by huangdali** [comment]
没有做任何限制哦
